# Generated by Django 4.0.2 on 2022-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, choices=[('FAMILY', 'Family'), ('FRIENDS', 'Friends'), ('RELATIVES', 'Relatives'), ('COWORKERS', 'Coworkers'), ('BUSINESS', 'Business')], max_length=48),
        ),
    ]
