# Generated by Django 4.0.2 on 2022-03-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_contact_address_alter_contact_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contactsapp.customer'),
        ),
    ]
