# Generated by Django 4.0.2 on 2022-03-02 04:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
