# Generated by Django 4.0.2 on 2022-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_contact_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer', max_length=96, null=True),
        ),
    ]
