# Generated by Django 4.0.2 on 2022-03-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
