# Generated by Django 4.0.2 on 2022-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0005_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text="Contact's email", max_length=96),
        ),
    ]
